### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by O4dg** [RYNEQ/proxy_checker#1]
Hello, thank you for this wonderful project, but I am learning the Rust language for the first time. Can you tell me how to run the tool and the necessary commands?

**Comment by RYNEQ** [comment]
Hi, you need Rust toolchain:
[https://www.rust-lang.org/tools/install](https://www.rust-lang.org/tools/install)

Then go to the cloned directory and for development run type :
`cargo run`

and for release build type:
`cargo build --release`
and then the executable will be in the `target/release/` directory
