### ISSUE TITLE
Strip Error 

### ISSUE THREAD

**Issue by R5ii** [RYNEQ/proxy_checker#2]
hello error installing strip

**Comment by RYNEQ** [comment]
cargo-strip or strip?  
can you provide your output please?

**Comment by R5ii** [comment]
I mean, the tape feature is I mean, the tape feature is unstable 
![A9D35EB5-F50D-4E41-9FF6-6EF0B1F1E1A3](https://user-images.githubusercontent.com/107008223/172357076-3a18c6ba-f465-42b7-a966-e754e8177bfa.jpeg)

**Comment by RYNEQ** [comment]
Your rust version is old, the strip feature is stabilized in `1.58` the current version is `1.61` , yours is `1.56`  
You can either update your rust (`rustup update`) or  remove the `strip = true` line from `Cargo.toml` file which is harmless  
I will add `rustc` version check which requires `1.56` itself ;)
